# Generated by Django 5.0.6 on 2024-05-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='user',
        ),
    ]
